# Generated by Django 5.1.3 on 2025-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_digilockerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
    ]
