name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: nehasharma2210/SankalpSetu

      - name: Show sync result
        run: echo "Has new commits: ${{ steps.sync.outputs.has_new_commits }}"
